#load_dataset:
datapath: ${nlb_paths.mc_maze}
bin_size: 20
phase   : val
dataset_name : mc_maze
dataset:
  _target_ : nlb_tools.nwb_interface.NWBDataset
  fpath    : ${..datapath}
  skip_fields :
    - hand_pos
    - cursor_pos
    - eye_pos
    - muscle_vel
    - muscle_len
    - joint_vel
    - joint_ang
    - force
preprocess :
  - method_name: resample
    args:
      - ${...bin_size}