_target_: utils.set_attributes
object:
  _target_      : dynamax.generalized_gaussian_ssm.poisson_models.PoissonLinearGaussianSSM
  state_dim     : 4
  emission_dim  : 5

model_name: LinearGaussianSSM_statedim${.object.state_dim}_emissiondim${.object.emission_dim}
initialize_kwargs  :
  emission_weights  :
    _target_: utils.empty_call
    func:
      _target_: compose.compose
      _args_:
        - _target_: jax.numpy.array
          _partial_: true
        - ${eval:'lambda x:x*4e-2'}
        - _target_  : numpy.random.normal
#        - _target_  : numpy.zeros
          _partial_ : true
#          shape :
          size :
            - ${.......object.emission_dim}
            - ${.......object.state_dim}
  emission_bias  :
    _target_: utils.empty_call
    func:
      _target_: compose.compose
      _args_:
        - _target_: jax.numpy.array
          _partial_: true

#        - _target_  : numpy.random.normal
        - _target_  : numpy.zeros
          _partial_ : true
          shape :
            - ${.......object.emission_dim}
#            - ${.......object.state_dim}