breakups:
  fit:
    train:
      trials_split: train
      neurons_split: [heldin,heldout]
    val:
      trials_split: val
      neurons_split: [heldin,heldout]

  k_shot_fit:
    input:
      trials_split: train
      neurons_split: heldin
    target:
      trials_split: train
      neurons_split: reallyheldout

  k_shot_test:
    input:
      trials_split: test
      neurons_split: heldin
    target:
      trials_split: test
      neurons_split: reallyheldout

  cosmoothing:
    input:
      trials_split: test
      neurons_split: heldin
    target:
      trials_split: test
      neurons_split: heldout

  decoding:
    fit:
      input:
        trials_split  : train
        neurons_split : heldin
      states:
        trials_split  : train
    test:
      input:
        trials_split  : test
        neurons_split : heldin
      states:
        trials_split  : test

  decoding_full:
    fit:
      input:
        trials_split  : train
        neurons_split : [heldin,heldout]
      states:
        trials_split  : train
    test:
      input:
        trials_split  : test
        neurons_split : [heldin,heldout]
      states:
        trials_split  : test
