defaults:
  - paths
  - data_organisation
  - breakups
  - load_dataset: mc_maze_small_20
  - path_to_save_files
#  - model@teacher : LinearGaussianSSM_offdiag
#  - model@student : LinearGaussianSSM
  - model@teacher : PoissonLinearGaussianSSM_offdiag
  - model@student : PoissonLinearGaussianSSM

#  - model@teacher : GaussianHmm
#  - model@student : GaussianHmm
  - optimizer : adam
  - decoding  : linear
  - _self_
####### multirun ##########
#  - hydra: state_dim_sweep
#  - hydra: num_state_sweep
#  - override hydra/launcher: joblib


#num_timesteps : 10
#train_trials : 10
#test_trials : 1000

num_timesteps : 35
#train_trials : 50
#test_trials : 25
train_trials : 5
test_trials : 70

#data_mode: student-teacher
data_mode: nlb

use_teacher_as_student  : false
#use_teacher_as_student  : true


optimizer :
  fit_kwargs  :
    optimizer   :
#      learning_rate : 5e-4
#      learning_rate : 5e-3
      learning_rate : 1e-3
    num_epochs  : 500
#      learning_rate : 1e-2
#    num_epochs  : 200

teacher :
  object  :
    emission_dim : 142

student :
  object  :
    state_dim : 7
    emission_dim : 142

teacher_path : results/teacher_${teacher.model_name}_train${train_trials}
result_save_path                              : ${teacher_path}/student_${student.model_name}_lr${optimizer.fit_kwargs.optimizer.learning_rate}_epochs${optimizer.fit_kwargs.num_epochs}
result_save_path_if_use_teacher_as_student    : ${teacher_path}/student_is_teacher
teacher_path_if_data_mode_nlb : results/nlb_${load_dataset.dataset_name}_${load_dataset.bin_size}_train${train_trials}

hyperparams_to_save:
  num_epochs  : ${optimizer.fit_kwargs.num_epochs}
  lr          : ${optimizer.fit_kwargs.optimizer.learning_rate}
  state_dim   : ${student.object.state_dim}


#####################

total_trials : ${eval:'(${train_trials}+${test_trials})'}


##### protocol ######

run_train    : true
save_student : true
load_student : true

analysis:
  sample_posterior                  : false
  plot_matrices                     : false
  compute_test_train_loglikelihood  : true
  compute_decoding                  : false
  save_results                      : true
  stats                             : true
